name: real_estate
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  cloud_firestore: ^1.0.7
  firebase_database: ^6.1.2
  firebase_core: ^1.0.3
  firebase_storage: ^8.0.5
  firebase_analytics: ^8.0.2
  # cupertino_icons: ^1.0.2
  modal_progress_hud: ^0.1.3
  firebase_auth: ^1.1.2
  intl: ^0.17.0
  persian_fonts: ^1.0.4
  image_picker: ^0.6.0+17
  shamsi_date: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/



#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: fonts/Pacifico-Regular.ttf
#
#    - family: Source Sans Pro
#      fonts:
#        - asset: fonts/SourceSansPro-Regular.ttf